# Generated by Django 4.1.3 on 2023-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0004_quizresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
